#pragma once


#include "Config.h"
#include "Defines.h"
#include "PlatformDetection.h"

#include "Hash/Hashable.h"
#include "Hash/HashFunctions.h"
#include "Hash/xxHash.h"

#include "Containers/DynamicArray.h"
#include "Containers/HashMap.h"
#include "Containers/LinkedList.h"
#include "Containers/StaticArray.h"

#include "Types/Base.h"
#include "Types/CompressedPair.h"
#include "Types/DataTypes.h"
#include "Types/Delegate.h"
#include "Types/Iterators.h"
#include "Types/Pair.h"
#include "Types/SharedPtr.h"
#include "Types/UniquePtr.h"
#include "Types/Version.h"

#include "Logging/Log.h"
#include "Logging/LogLevel.h"

#include "Math/Math.h"
#include "Math/Vector2.h"
#include "Math/Vector3.h"

#include "TypeTraits/Conjunction.h"
#include "TypeTraits/Decay.h"
#include "TypeTraits/EnableIf.h"
#include "TypeTraits/IsBitwiseConstructible.h"
#include "TypeTraits/IsCharTypeSupported.h"
#include "TypeTraits/IsCopyAssignable.h"
#include "TypeTraits/IsCopyConstructible.h"
#include "TypeTraits/IsMoveAssignable.h"
#include "TypeTraits/IsMoveConstructible.h"
#include "TypeTraits/IsReference.h"
#include "TypeTraits/IsScalar.h"
#include "TypeTraits/IsStandardLayout.h"
#include "TypeTraits/IsZeroConstructType.h"
#include "TypeTraits/Logical.h"
#include "TypeTraits/MakeSigned.h"
#include "TypeTraits/MakeUnsigned.h"
#include "TypeTraits/PrimaryTypes.h"
#include "TypeTraits/RemoveAllExtents.h"
#include "TypeTraits/RemoveCV.h"
#include "TypeTraits/RemoveCVRef.h"
#include "TypeTraits/RemoveExtent.h"
#include "TypeTraits/RemoveReference.h"
#include "TypeTraits/Trivial.h"
#include "TypeTraits/TypeChooser.h"
#include "TypeTraits/TypeRelationships.h"

#include "Utilities/CommandLine.h"
#include "Utilities/NonCopyable.h"
#include "Utilities/NonMovable.h"
#include "Utilities/OutputStream.h"
#include "Utilities/Singleton.h"

#include "String/String.h"
#include "String/PathUtils.h"
#include "String/StringConversion.h"

#include "Threading/ScopeLock.h"
#include "Threading/Mutex.h"
#include "Threading/Thread.h"

#include "Memory/Memory.h"