#pragma once

#include "Config.h"
#include "Defines.h"
#include "PlatformDetection.h"

#include "Types/Base.h"
#include "Types/DataTypes.h"

#include "TypeTraits/Decay.h"
#include "TypeTraits/EnableIf.h"
#include "TypeTraits/IsBitwiseConstructible.h"
#include "TypeTraits/IsCopyAssignable.h"
#include "TypeTraits/IsCopyConstructible.h"
#include "TypeTraits/IsMoveAssignable.h"
#include "TypeTraits/IsMoveConstructible.h"
#include "TypeTraits/IsReference.h"
#include "TypeTraits/IsScalar.h"
#include "TypeTraits/IsStandardLayout.h"
#include "TypeTraits/IsZeroConstructType.h"
#include "TypeTraits/Logical.h"
#include "TypeTraits/PrimaryTypes.h"
#include "TypeTraits/RemoveCV.h"
#include "TypeTraits/RemoveCVRef.h"
#include "TypeTraits/RemoveExtent.h"
#include "TypeTraits/RemoveReference.h"
#include "TypeTraits/Trivial.h"
#include "TypeTraits/TypeRelationships.h"